### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mythris29** [wow-addon/FarmIt2#1]
I'm seeing this error on startup with the addon enabled 

459x Couldn't find inherited node: ItemButtonTemplate

Let me know if you need further info.

**Comment by davidcraig** [comment]
Hi, I suspect you are not on the latest version of the addon, I fixed this particular issue in this commit: 347283f4bf0aa054b5d4b2916880b6217ee49207

And I am running fine without any issues:
![image](https://user-images.githubusercontent.com/11975187/88476322-5eda5180-cf2f-11ea-9371-2f256ec8ac56.png)

Did you install the addon by cloning it into your wow addons folder? if so you should just need to do a `git pull` to get the latest version (this is not on curse as I am not the original author, however the 'official' addon has not been updated by the author for several years hence I decided to host the fixed version here).

Let me know if you need any help :)

**Comment by Mythris29** [comment]
...Yup I'm sorry for wasting your time this was an issue on my end. I was troubleshooting another issue and had backed up my addons folder to a second explorer window...which I then updated the backup to this code and not the live retail version lol 

Very embarrassing and I apologize. Your version seems to be working well for me so far. Can't wait to see you published with Farmit3 I've really been missing this addon and you made my day when I realized somebody was working on it again! Thank you!

**Comment by davidcraig** [comment]
No problem at all, happy to have helped.

It is a lot of hassle sometimes taking ownership of addons with curse's policies etc, but I do believe that we should be able to keep them maintained as long as someone finds it useful, that's why I bring any I fix into this GitHub organisation (at least until the owners pick them back up if they ever do), but also with GitHub it's not just on one person any more, if I stop writing code i'll at least review and merge any useful pull requests :D
